version: "3.8"
services:
  db:
    image: postgres:16.2
    environment:
      POSTGRES_DB: transport_insurance
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: admin_user
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
